#include <jni.h>
#include <android/log.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>
#include <elf.h>
#include <sys/mman.h>
#include <unistd.h>
#include <pthread.h>

#define TAG "LuaDebugger"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, TAG, __VA_ARGS__)

typedef struct lua_State lua_State;
typedef struct lua_Debug lua_Debug;
typedef void   (*lua_Hook)(lua_State*, lua_Debug*);
typedef lua_State* (*luaL_newstate_t)(void);
typedef void       (*lua_sethook_t)(lua_State*, lua_Hook, int, int);
typedef int        (*lua_getinfo_t)(lua_State*, const char*, lua_Debug*);
typedef int        (*lua_getstack_t)(lua_State*, int, lua_Debug*);

#define LUA_MASKCALL 1

struct lua_Debug {
    int event;
    const char* name;
    const char* namewhat;
    const char* what;
    const char* source;
    int currentline;
    int nups;
    int linedefined;
    int lastlinedefined;
    char short_src[60];
    int i_ci;
};

static luaL_newstate_t g_orig_newstate = NULL;
static lua_sethook_t   g_sethook       = NULL;
static lua_getinfo_t   g_getinfo       = NULL;
static lua_getstack_t  g_getstack      = NULL;
static char            g_target[128]   = {0};

// ── Global API list dari api_dump ─────────────────────────────
static const char* GLOBAL_API[] = {
    "Vector3D",
    "activateGarage",
    "activateHeliSpeedCheat",
    "activateInteriorPeds",
    "activateMenuItem",
    "activatePimpCheat",
    "activateSaveMenu",
    "addAmmoToChar",
    "addArmourToChar",
    "addAttractor",
    "addBigGunFlash",
    "addBlipForCar",
    "addBlipForCarOld",
    "addBlipForChar",
    "addBlipForCoord",
    "addBlipForCoordOld",
    "addBlipForDeadChar",
    "addBlipForObject",
    "addBlipForPickup",
    "addBlipForSearchlight",
    "addBlood",
    "addButtonFlag",
    "addCharDecisionMakerEventResponse",
    "addEventHandler",
    "addExplosion",
    "addExplosionNoSound",
    "addExplosionVariableShake",
    "addGroupDecisionMakerEventResponse",
    "addHospitalRestart",
    "addNextMessageToPreviousBriefs",
    "addOneOffSound",
    "addPedtypeAsAttractorUser",
    "addPoliceRestart",
    "addPriceModifier",
    "addSetPiece",
    "addShopItem",
    "addShortRangeSpriteBlipForContactPoint",
    "addShortRangeSpriteBlipForCoord",
    "addSmokeParticle",
    "addSparks",
    "addSphere",
    "addSpriteBlipForContactPoint",
    "addSpriteBlipForCoord",
    "addStuckCarCheck",
    "addStuckCarCheckWithWarp",
    "addStuntJump",
    "addToCarRotationVelocity",
    "addToObjectRotationVelocity",
    "addToObjectVelocity",
    "addUpsidedownCarCheck",
    "addVehicleMod",
    "addVelocityRelativeToObjectVelocity",
    "addWidgetFlag",
    "allocateMemory",
    "allocateStreamedScriptToObject",
    "allocateStreamedScriptToRandomPed",
    "allowFixedCameraCollision",
    "allowPauseInWidescreen",
    "alterWantedLevel",
    "alterWantedLevelNoDrop",
    "anchorBoat",
    "applyBrakesToPlayersCar",
    "applyForceToCar",
    "areAnyCarCheatsActivated",
    "areAnyCharsNearChar",
    "areCreditsFinished",
    "areMeasurementsInMetres",
    "areSubtitlesSwitchedOn",
    "assert",
    "attachAnimsToModel",
    "attachCameraToChar",
    "attachCameraToCharLookAtChar",
    "attachCameraToVehicle",
    "attachCameraToVehicleLookAtChar",
    "attachCameraToVehicleLookAtVehicle",
    "attachCarToCar",
    "attachCarToObject",
    "attachCharToBike",
    "attachCharToCar",
    "attachCharToObject",
    "attachFxSystemToCharBone",
    "attachMissionAudioToCar",
    "attachMissionAudioToChar",
    "attachMissionAudioToObject",
    "attachObjectToCar",
    "attachObjectToChar",
    "attachObjectToObject",
    "attachSearchlightToSearchlightObject",
    "attachTrailerToCab",
    "attachWinchToHeli",
    "autoSave",
    "awardPlayerMissionRespect",
    "boatGotoCoords",
    "boatStop",
    "breakObject",
    "buildPlayerModel",
    "burstCarTire",
    "buyItem",
    "cameraIsVectorMoveRunning",
    "cameraIsVectorTrackRunning",
    "cameraPersistFov",
    "cameraPersistPos",
    "cameraPersistTrack",
    "cameraResetNewScriptables",
    "cameraSetLerpFov",
    "cameraSetShakeSimulationSimple",
    "cameraSetVectorMove",
    "cameraSetVectorTrack",
    "canCharSeeDeadChar",
    "canTriggerGangWarWhenOnAMission",
    "cancelOverrideRestart",
    "carGotoCoordinates",
    "carGotoCoordinatesAccurate",
    "carGotoCoordinatesRacing",
    "carSetIdle",
    "carWanderRandomly",
    "changeBlipColour",
    "changeBlipDisplay",
    "changeBlipScale",
    "changeCarColour",
    "changeCarColourFromMenu",
    "changeGarageType",
    "changePlaybackToUseAi",
    "checkpointSave",
    "checkpointSaveOddjob",
    "clearAllCharRelationships",
    "clearAllScriptFireFlags",
    "clearAllScriptRoadblocks",
    "clearArea",
    "clearAreaOfCars",
    "clearAreaOfChars",
    "clearAttractor",
    "clearCarLastDamageEntity",
    "clearCarLastWeaponDamage",
    "clearCharDecisionMakerEventResponse",
    "clearCharLastDamageEntity",
    "clearCharLastWeaponDamage",
    "clearCharRelationship",
    "clearCharTasks",
    "clearCharTasksImmediately",
    "clearConversationForChar",
    "clearCutscene",
    "clearExtraColours",
    "clearGroupDecisionMakerEventResponse",
    "clearGxtEntry",
    "clearHeliOrientation",
    "clearHelp",
    "clearLastBuildingModelShotByPlayer",
    "clearLoadedShop",
    "clearLookAt",
    "clearMissionAudio",
    "clearObjectLastWeaponDamage",
    "clearOnscreenCounter",
    "clearOnscreenTimer",
    "clearPrints",
    "clearRelationship",
    "clearSequenceTask",
    "clearSkip",
    "clearSmallPrints",
    "clearSpecificZonesToTriggerGangWar",
    "clearThisBigPrint",
    "clearThisPrint",
    "clearThisPrintBigNow",
    "clearWantedLevel",
    "clearWantedLevelInGarage",
    "closeAllCarDoors",
    "closeGarage",
    "closeSequenceTask",
    "collectgarbage",
    "connectLods",
    "controlCarDoor",
    "controlCarHydraulics",
    "controlMovableVehiclePart",
    "convert3DCoordsToScreen",
    "convert3DCoordsToScreenEx",
    "convertGameScreenCoordsToWindowScreenCoords",
    "convertMatrixToQuaternion",
    "convertMetresToFeet",
    "convertMetresToFeetInt",
    "convertQuaternionToMatrix",
    "convertScreenCoordsToWorld3D",
    "convertWindowScreenCoordsToGameScreenCoords",
    "copyCharDecisionMaker",
    "copyGroupDecisionMaker",
    "copySharedCharDecisionMaker",
    "createBirds",
    "createCar",
    "createCarGenerator",
    "createCarGeneratorWithPlate",
    "createChar",
    "createCharAsPassenger",
    "createCharAtAttractor",
    "createCharInsideCar",
    "createCheckpoint",
    "createDirectory",
    "createEmergencyServicesCar",
    "createForsalePropertyPickup",
    "createFxSystem",
    "createFxSystemOnCar",
    "createFxSystemOnCarWithDirection",
    "createFxSystemOnChar",
    "createFxSystemOnCharWithDirection",
    "createFxSystemOnObject",
    "createFxSystemOnObjectWithDirection",
    "createGroup",
    "createHorseshoePickup",
    "createLockedPropertyPickup",
    "createMenu",
    "createMenuGrid",
    "createMissionTrain",
    "createMoneyPickup",
    "createObject",
    "createObjectNoOffset",
    "createOysterPickup",
    "createPickup",
    "createPickupWithAmmo",
    "createPlayer",
    "createProtectionPickup",
    "createRandomCarForCarPark",
    "createRandomChar",
    "createRandomCharAsDriver",
    "createRandomCharAsPassenger",
    "createScriptRoadblock",
    "createSearchlight",
    "createSearchlightOnVehicle",
    "createShopWidget",
    "createSnapshotPickup",
    "createSwatRope",
    "createUser3dMarker",
    "customPlateDesignForNextCar",
    "customPlateForNextCar",
    "damageCarDoor",
    "damageCarPanel",
    "damageChar",
    "deactivateGarage",
    "declareMissionFlag",
    "decodeJson",
    "decrementFloatStat",
    "decrementIntStat",
    "deleteAllTrains",
    "deleteCar",
    "deleteChar",
    "deleteCheckpoint",
    "deleteMenu",
    "deleteMissionTrain",
    "deleteMissionTrains",
    "deleteObject",
    "deletePlayer",
    "deleteSearchlight",
    "deleteWidget",
    "detachCar",
    "detachCharFromCar",
    "detachObject",
    "detachTrailerFromCab",
    "disableAllEntryExits",
    "disableCharSpeech",
    "disableHeliAudio",
    "disablePlayerSprint",
    "displayCarNames",
    "displayHud",
    "displayNonMinigameHelpMessages",
    "displayNthOnscreenCounterWithString",
    "displayOnscreenCounterWithString",
    "displayOnscreenTimer",
    "displayOnscreenTimerWithString",
    "displayRadar",
    "displayText",
    "displayTextClamped",
    "displayTextWidget",
    "displayTextWith2Numbers",
    "displayTextWithFloat",
    "displayTextWithNumber",
    "displayTextWithNumberClamped",
    "displayZoneNames",
    "do2dRectanglesCollide",
    "doCameraBump",
    "doFade",
    "doMissionSkip",
    "doWeaponStuffAtStartOf2pGame",
    "doesBlipExist",
    "doesCarHaveHydraulics",
    "doesCarHaveStuckCarCheck",
    "doesCharExist",
    "doesDecisionMakerExist",
    "doesDirectoryExist",
    "doesFileExist",
    "doesGroupExist",
    "doesObjectExist",
    "doesObjectHaveThisModel",
    "doesPickupExist",
    "doesScriptFireExist",
    "doesSearchlightExist",
    "doesVehicleExist",
    "dofile",
    "dontRemoveChar",
    "dontRemoveObject",
    "dontSuppressAnyCarModels",
    "dontSuppressCarModel",
    "drawCorona",
    "drawCrosshair",
    "drawLightWithRange",
    "drawOddjobTitleBeforeFade",
    "drawRect",
    "drawShadow",
    "drawSphere",
    "drawSprite",
    "drawSpriteWithRotation",
    "drawSubtitlesBeforeFade",
    "drawWeaponshopCorona",
    "drawWindow",
    "dropObject",
    "dropSecondObject",
    "enableAmbientCrime",
    "enableBurglaryHouses",
    "enableCharSpeech",
    "enableConversation",
    "enableCraneControls",
    "enableDisabledAttractorsOnObject",
    "enableEntryExitPlayerGroupWarping",
    "encodeJson",
    "ensurePlayerHasDriveByWeapon",
    "error",
    "explodeCar",
    "explodeCarInCutscene",
    "explodeCarInCutsceneShakeAndBits",
    "explodeCharHead",
    "extendPatrolRoute",
    "extendRoute",
    "extinguishFireAtPoint",
    "failCurrentMission",
    "failKillFrenzy",
    "fetchNextCard",
    "findAllRandomCharsInSphere",
    "findAllRandomObjectsInSphere",
    "findAllRandomVehiclesInSphere",
    "findMaxNumberOfGroupMembers",
    "findNumberTagsTagged",
    "findTrainDirection",
    "finishSettingUpConversation",
    "finishSettingUpConversationNoSubtitles",
    "fireHunterGun",
    "fireSingleBullet",
    "fixCar",
    "fixCarDoor",
    "fixCarPanel",
    "fixCarTire",
    "flashHudObject",
    "flushPatrolRoute",
    "flushRoute",
    "forceAllVehicleLightsOff",
    "forceBigMessageAndCounter",
    "forceCarLights",
    "forceDeathRestart",
    "forceInteriorLightingForPlayer",
    "forceWeather",
    "forceWeatherNow",
    "freeMemory",
    "freezeCarPosition",
    "freezeCarPositionAndDontLoadCollision",
    "freezeCharPosition",
    "freezeCharPositionAndDontLoadCollision",
    "freezeObjectPosition",
    "freezeOnscreenTimer",
    "gcinfo",
    "get2dLinesIntersectPoint",
    "getActiveCameraCoordinates",
    "getActiveCameraPointAt",
    "getActiveInterior",
    "getAllChars",
    "getAllObjects",
    "getAllVehicles",
    "getAmmoInCharWeapon",
    "getAngleBetween2dVectors",
    "getAudioStreamLength",
    "getAudioStreamState",
    "getAudioStreamVolume",
    "getAvailableVehicleMod",
    "getBeatProximity",
    "getBeatTrackStatus",
    "getCameraFov",
    "getCarBlockingCar",
    "getCarCharIsUsing",
    "getCarColours",
    "getCarCoordinates",
    "getCarCurrentGear",
    "getCarDoorLockStatus",
    "getCarForwardX",
    "getCarForwardY",
    "getCarHeading",
    "getCarHealth",
    "getCarMass",
    "getCarModel",
    "getCarModelValue",
    "getCarMovingComponentOffset",
    "getCarNumberOfGears",
    "getCarPitch",
    "getCarPointer",
    "getCarRoll",
    "getCarSpeed",
    "getCarSpeedVector",
    "getCarUprightValue",
    "getCharActiveInterior",
    "getCharAnimCurrentTime",
    "getCharAnimTotalTime",
    "getCharArmour",
    "getCharCoordinates",
    "getCharHeading",
    "getCharHealth",
    "getCharHeightAboveGround",
    "getCharHighestPriorityEvent",
    "getCharInCarPassengerSeat",
    "getCharModel",
    "getCharPlayerIsTargeting",
    "getCharPointer",
    "getCharPointerHandle",
    "getCharQuaternion",
    "getCharSpeed",
    "getCharSwimState",
    "getCharVelocity",
    "getCharWeaponInSlot",
    "getCityFromCoords",
    "getCityPlayerIsIn",
    "getClipboardText",
    "getClosestCarNode",
    "getClosestCarNodeWithHeading",
    "getClosestCharNode",
    "getClosestStealableObject",
    "getClosestStraightRoad",
    "getClothesItem",
    "getControllerMode",
    "getCurrentCarMod",
    "getCurrentCharWeapon",
    "getCurrentDate",
    "getCurrentDayOfWeek",
    "getCurrentLanguage",
    "getCurrentPopulationZoneType",
    "getCurrentVehiclePaintjob",
    "getCutsceneOffset",
    "getCutsceneTime",
    "getDeadCharCoordinates",
    "getDeadCharPickupCoords",
    "getDebugCameraCoordinates",
    "getDebugCameraPointAt",
    "getDistanceBetweenCoords2d",
    "getDistanceBetweenCoords3d",
    "getDoorAngleRatio",
    "getDriverOfCar",
    "getExtraCarColours",
    "getFadingStatus",
    "getFloatStat",
    "getFreeGxtKey",
    "getGameDirectory",
    "getGameTimer",
    "getGroundZFor3dCoord",
    "getGroupMember",
    "getGroupSize",
    "getGxtText",
    "getHashKey",
    "getHeadingFromVector2d",
    "getHudColour",
    "getIntStat",
    "getItemInShop",
    "getLevelDesignCoordsForObject",
    "getLoadedShop",
    "getMaxWantedLevel",
    "getMaximumNumberOfPassengers",
    "getMenuItemAccepted",
    "getMenuItemSelected",
    "getMinutesToTimeOfDay",
    "getMissionNum",
    "getMissionPage",
    "getModelDimensions",
    "getMoonloaderVersion",
    "getNameOfEntryExitCharUsed",
    "getNameOfInfoZone",
    "getNameOfItem",
    "getNameOfZone",
    "getNearestTagPosition",
    "getNthClosestCarNode",
    "getNthClosestCarNodeWithHeading",
    "getNumAvailablePaintjobs",
    "getNumCarColours",
    "getNumOfModelsKilledByPlayer",
    "getNumberOfFiresInArea",
    "getNumberOfFiresInRange",
    "getNumberOfFollowers",
    "getNumberOfInstancesOfStreamedScript",
    "getNumberOfItemsInShop",
    "getNumberOfPassengers",
    "getObjectAnimCurrentTime",
    "getObjectCoordinates",
    "getObjectHeading",
    "getObjectHealth",
    "getObjectMass",
    "getObjectModel",
    "getObjectPointer",
    "getObjectPointerHandle",
    "getObjectQuaternion",
    "getObjectRotationVelocity",
    "getObjectSpeed",
    "getObjectTurnMass",
    "getObjectVelocity",
    "getOffsetFromCarInWorldCoords",
    "getOffsetFromCharInWorldCoords",
    "getOffsetFromObjectInWorldCoords",
    "getPadState",
    "getParkingNodeInArea",
    "getPcMouseMovement",
    "getPedType",
    "getPercentageTaggedInArea",
    "getPickupCoordinates",
    "getPlaneUndercarriagePosition",
    "getPlayerChar",
    "getPlayerGroup",
    "getPlayerInCarCameraMode",
    "getPlayerMaxArmour",
    "getPlayerMoney",
    "getPositionOfAnalogueSticks",
    "getPositionOfEntryExitCharUsed",
    "getPriceOfItem",
    "getProgressPercentage",
    "getRadioChannel",
    "getRandomCarInSphereNoSave",
    "getRandomCarModelInMemory",
    "getRandomCarOfTypeInAngledAreaNoSave",
    "getRandomCarOfTypeInArea",
    "getRandomCarOfTypeInAreaNoSave",
    "getRandomCharInAreaOffsetNoSave",
    "getRandomCharInSphere",
    "getRandomCharInSphereNoBrain",
    "getRandomCharInSphereOnlyDrugsBuyers",
    "getRandomCharInZone",
    "getRemoteControlledCar",
    "getRidOfPlayerProstitute",
    "getRopeHeightForObject",
    "getScreenResolution",
    "getScriptFireCoords",
    "getScriptTaskStatus",
    "getSequenceProgress",
    "getSequenceProgressRecursive",
    "getShoppingExtraInfo",
    "getSoundLevelAtCoords",
    "getStringWidth",
    "getStringWidthWithNumber",
    "getStructElement",
    "getStructFloatElement",
    "getTargetBlipCoordinates",
    "getTerritoryUnderControlPercentage",
    "getTimeOfDay",
    "getTotalNumberOfPedsKilledByPlayer",
    "getTrainCaboose",
    "getTrainCarriage",
    "getUserOfClosestMapAttractor",
    "getVehicleClass",
    "getVehicleModType",
    "getVehiclePointerHandle",
    "getVehicleQuaternion",
    "getWaterHeightAtCoords",
    "getWeapontypeModel",
    "getWeapontypeSlot",
    "getWheelieStats",
    "getWidgetPosition",
    "getWidgetValue",
    "getWidgetValue2",
    "getWorkingDirectory",
    "getZoneDealerStrength",
    "getZoneGangStrength",
    "getfenv",
    "getmetatable",
    "giveMeleeAttackToChar",
    "giveNonPlayerCarNitro",
    "givePlayerClothes",
    "givePlayerClothesOutsideShop",
    "givePlayerMoney",
    "giveRemoteControlledModelToPlayer",
    "giveVehiclePaintjob",
    "giveWeaponToChar",
    "grabEntityOnRopeForObject",
    "grabEntityOnWinch",
    "hasAnimationLoaded",
    "hasCarBeenDamagedByCar",
    "hasCarBeenDamagedByChar",
    "hasCarBeenDamagedByWeapon",
    "hasCarBeenResprayed",
    "hasCarRecordingBeenLoaded",
    "hasCharBeenArrested",
    "hasCharBeenDamagedByCar",
    "hasCharBeenDamagedByChar",
    "hasCharBeenDamagedByWeapon",
    "hasCharBeenPhotographed",
    "hasCharGotWeapon",
    "hasCharSpottedChar",
    "hasCharSpottedCharInFront",
    "hasCutsceneFinished",
    "hasCutsceneLoaded",
    "hasDeatharrestBeenExecuted",
    "hasGameJustReturnedFromFrontend",
    "hasLanguageChanged",
    "hasMissionAudioFinished",
    "hasMissionAudioLoaded",
    "hasModelLoaded",
    "hasObjectBeenDamaged",
    "hasObjectBeenDamagedByWeapon",
    "hasObjectBeenPhotographed",
    "hasObjectBeenUprooted",
    "hasObjectCollidedWithAnything",
    "hasObjectOfTypeBeenSmashed",
    "hasPickupBeenCollected",
    "hasPlayerBoughtItem",
    "hasSaveGameFinished",
    "hasSpecialCharacterLoaded",
    "hasStreamedScriptLoaded",
    "hasTrainDerailed",
    "hasVehicleModLoaded",
    "heliAttackPlayer",
    "heliFollowEntity",
    "heliGotoCoords",
    "heliKeepEntityInView",
    "heliLandAtCoords",
    "hidImplements",
    "hideAllFrontendBlips",
    "hideCharWeaponForScriptedCutscene",
    "highlightMenuItem",
    "ignoreHeightDifferenceFollowingNodes",
    "import",
    "improveCarByCheating",
    "increasePlayerMaxArmour",
    "increasePlayerMaxHealth",
    "incrementFloatStat",
    "incrementFloatStatNoMessage",
    "incrementIntStat",
    "incrementIntStatNoMessage",
    "initZonePopulationSettings",
    "ipairs",
    "is2playerGameGoingOn",
    "isAnyPickupAtCoords",
    "isAreaOccupied",
    "isAttachedPlayerHeadingAchieved",
    "isBigVehicle",
    "isButtonPressed",
    "isCarDead",
    "isCarDoorDamaged",
    "isCarDoorFullyOpen",
    "isCarEngineOn",
    "isCarInAirProper",
    "isCarInArea2d",
    "isCarInArea3d",
    "isCarInWater",
    "isCarLowRider",
    "isCarModel",
    "isCarOnFire",
    "isCarOnScreen",
    "isCarPassengerSeatFree",
    "isCarSirenOn",
    "isCarStopped",
    "isCarStoppedInArea2d",
    "isCarStoppedInArea3d",
    "isCarStreetRacer",
    "isCarStuck",
    "isCarStuckOnRoof",
    "isCarTireBurst",
    "isCarTouchingCar",
    "isCarUpright",
    "isCarUpsidedown",
    "isCarVisiblyDamaged",
    "isCarWaitingForWorldCollision",
    "isCharAtScriptedAttractor",
    "isCharAttachedToAnyCar",
    "isCharDead",
    "isCharDucking",
    "isCharGettingInToACar",
    "isCharHeadMissing",
    "isCharHoldingObject",
    "isCharInAir",
    "isCharInAngledArea2d",
    "isCharInAngledArea3d",
    "isCharInAngledAreaInCar2d",
    "isCharInAngledAreaInCar3d",
    "isCharInAngledAreaOnFoot2d",
    "isCharInAngledAreaOnFoot3d",
    "isCharInAnyBoat",
    "isCharInAnyCar",
    "isCharInAnyHeli",
    "isCharInAnyPlane",
    "isCharInAnyPoliceVehicle",
    "isCharInAnySearchlight",
    "isCharInAnyTrain",
    "isCharInArea2d",
    "isCharInArea3d",
    "isCharInAreaInCar2d",
    "isCharInAreaInCar3d",
    "isCharInAreaOnFoot2d",
    "isCharInAreaOnFoot3d",
    "isCharInCar",
    "isCharInFlyingVehicle",
    "isCharInModel",
    "isCharInSearchlight",
    "isCharInTaxi",
    "isCharInWater",
    "isCharInZone",
    "isCharMale",
    "isCharModel",
    "isCharOnAnyBike",
    "isCharOnFoot",
    "isCharOnScreen",
    "isCharPlayingAnim",
    "isCharRespondingToEvent",
    "isCharShooting",
    "isCharShootingInArea",
    "isCharSittingInAnyCar",
    "isCharSittingInCar",
    "isCharStopped",
    "isCharStoppedInAngledArea2d",
    "isCharStoppedInAngledArea3d",
    "isCharStoppedInAngledAreaInCar2d",
    "isCharStoppedInAngledAreaInCar3d",
    "isCharStoppedInAngledAreaOnFoot2d",
    "isCharStoppedInAngledAreaOnFoot3d",
    "isCharStoppedInArea2d",
    "isCharStoppedInArea3d",
    "isCharStoppedInAreaInCar2d",
    "isCharStoppedInAreaInCar3d",
    "isCharStoppedInAreaOnFoot2d",
    "isCharStoppedInAreaOnFoot3d",
    "isCharStuckUnderCar",
    "isCharSwimming",
    "isCharTalking",
    "isCharTouchingChar",
    "isCharTouchingObject",
    "isCharTouchingObjectOnFoot",
    "isCharTouchingVehicle",
    "isCharUsingMapAttractor",
    "isCharWaitingForWorldCollision",
    "isCheckpointResuming",
    "isCleoLoaded",
    "isClosestObjectOfTypeSmashedOrDamaged",
    "isConversationAtNode",
    "isCopVehicleInArea3dNoSave",
    "isCurrentCharWeapon",
    "isCursorActive",
    "isDebugCameraOn",
    "isEmergencyServicesVehicle",
    "isExplosionInArea",
    "isFinalbuild",
    "isFlameInAngledArea2d",
    "isFlameInAngledArea3d",
    "isGamePaused",
    "isGangWarFightingGoingOn",
    "isGangWarGoingOn",
    "isGarageClosed",
    "isGarageOpen",
    "isGroupLeader",
    "isGroupMember",
    "isHelpMessageBeingDisplayed",
    "isHidPressed",
    "isHidReleased",
    "isLastBuildingModelShotByPlayer",
    "isLineOfSightClear",
    "isMessageBeingDisplayed",
    "isMinigameInProgress",
    "isModelAvailable",
    "isModelInCdimage",
    "isMoneyPickupAtCoords",
    "isMouseUsingVerticalInversion",
    "isNextStationAllowed",
    "isNightVisionActive",
    "isObjectAttached",
    "isObjectInAngledArea2d",
    "isObjectInAngledArea3d",
    "isObjectInArea2d",
    "isObjectInArea3d",
    "isObjectInWater",
    "isObjectIntersectingWorld",
    "isObjectOnScreen",
    "isObjectPlayingAnim",
    "isObjectStatic",
    "isObjectWithinBrainActivationRange",
    "isOpcodesAvailable",
    "isPauseMenuActive",
    "isPcUsingJoypad",
    "isPcVersion",
    "isPlaybackGoingOnForCar",
    "isPlayerClimbing",
    "isPlayerControlLocked",
    "isPlayerControlOn",
    "isPlayerControllable",
    "isPlayerDead",
    "isPlayerInInfoZone",
    "isPlayerInPositionForConversation",
    "isPlayerInRemoteMode",
    "isPlayerPerformingStoppie",
    "isPlayerPerformingWheelie",
    "isPlayerPlaying",
    "isPlayerPressingHorn",
    "isPlayerTargettingAnything",
    "isPlayerTargettingChar",
    "isPlayerTargettingObject",
    "isPlayerUsingJetpack",
    "isPlayerWearing",
    "isPointObscuredByAMissionEntity",
    "isPointOnScreen",
    "isProceduralInteriorActive",
    "isProjectileInArea",
    "isRelationshipSet",
    "isSampAvailable",
    "isSampLoaded",
    "isSampfuncsLoaded",
    "isScriptFireExtinguished",
    "isSkipCutsceneButtonPressed",
    "isSkipWaitingForScriptToFadeIn",
    "isThisHelpMessageBeingDisplayed",
    "isThisModelABoat",
    "isThisModelACar",
    "isThisModelAHeli",
    "isThisModelAPlane",
    "isTouchEnabled",
    "isTrailerAttachedToCab",
    "isVehicleAttached",
    "isVehicleInSearchlight",
    "isVehicleOnAllWheels",
    "isVehicleTouchingObject",
    "isWantedLevelGreater",
    "isWidescreenOnInOptions",
    "isWidgetDoubletapped",
    "isWidgetPressed",
    "isWidgetPressedEx",
    "isWidgetReleased",
    "isWidgetSwiped",
    "isWidgetSwipedLeft",
    "isWidgetSwipedRight",
    "killFxSystem",
    "killFxSystemNow",
    "limitAngle",
    "limitTwoPlayerDistance",
    "linkObjectToInterior",
    "listenToPlayerGroupCommands",
    "load",
    "load3dAudioStream",
    "load3dAudioStreamFromMemory",
    "loadAllModelsNow",
    "loadAllStreamingModels",
    "loadAndLaunchMissionInternal",
    "loadAudioStream",
    "loadAudioStreamFromMemory",
    "loadCharDecisionMaker",
    "loadCutscene",
    "loadGroupDecisionMaker",
    "loadMissionAudio",
    "loadMissionText",
    "loadPathNodesInArea",
    "loadPrices",
    "loadScene",
    "loadSceneInDirection",
    "loadShop",
    "loadSpecialCharacter",
    "loadSprite",
    "loadTextureDictionary",
    "loadfile",
    "loadstring",
    "locateCar2d",
    "locateCar3d",
    "locateCharAnyMeans2d",
    "locateCharAnyMeans3d",
    "locateCharAnyMeansCar2d",
    "locateCharAnyMeansCar3d",
    "locateCharAnyMeansChar2d",
    "locateCharAnyMeansChar3d",
    "locateCharAnyMeansObject2d",
    "locateCharAnyMeansObject3d",
    "locateCharInCar2d",
    "locateCharInCar3d",
    "locateCharInCarCar2d",
    "locateCharInCarCar3d",
    "locateCharInCarChar2d",
    "locateCharInCarChar3d",
    "locateCharInCarObject2d",
    "locateCharInCarObject3d",
    "locateCharOnFoot2d",
    "locateCharOnFoot3d",
    "locateCharOnFootCar2d",
    "locateCharOnFootCar3d",
    "locateCharOnFootChar2d",
    "locateCharOnFootChar3d",
    "locateCharOnFootObject2d",
    "locateCharOnFootObject3d",
    "locateObject2d",
    "locateObject3d",
    "locateStoppedCar2d",
    "locateStoppedCar3d",
    "locateStoppedCharAnyMeans2d",
    "locateStoppedCharAnyMeans3d",
    "locateStoppedCharInCar2d",
    "locateStoppedCharInCar3d",
    "locateStoppedCharOnFoot2d",
    "locateStoppedCharOnFoot3d",
    "lockCarDoors",
    "lockDoor",
    "lockPlayerControl",
    "main",
    "makeHeliComeCrashingDown",
    "makeObjectTargettable",
    "makePlayerFireProof",
    "makePlayerGangDisappear",
    "makePlayerGangReappear",
    "makePlayerSafe",
    "makeRoomInPlayerGangForMissionPeds",
    "manageAllPopulation",
    "markCarAsConvoyCar",
    "markCarAsNoLongerNeeded",
    "markCharAsNoLongerNeeded",
    "markMissionTrainAsNoLongerNeeded",
    "markMissionTrainsAsNoLongerNeeded",
    "markModelAsNoLongerNeeded",
    "markObjectAsNoLongerNeeded",
    "markRoadNodeAsDontWander",
    "markStreamedScriptAsNoLongerNeeded",
    "markVehicleModAsNoLongerNeeded",
    "module",
    "monet_cp1251_to_utf8",
    "monet_is_audiostream_available",
    "monet_utf8_to_cp1251",
    "moveSearchlightBetweenCoords",
    "newproxy",
    "next",
    "openCarDoor",
    "openCarDoorABit",
    "openGarage",
    "openSequenceTask",
    "overrideNextRestart",
    "pairs",
    "pauseCurrentBeatTrack",
    "pausePlaybackRecordedCar",
    "pcall",
    "performSequenceTask",
    "performSequenceTaskFromProgress",
    "placeObjectRelativeToCar",
    "planeAttackPlayer",
    "planeAttackPlayerUsingDogFight",
    "planeFlyInDirection",
    "planeFollowEntity",
    "planeGotoCoords",
    "planeStartsInAir",
    "playAndKillFxSystem",
    "playBeatTrack",
    "playFxSystem",
    "playMissionAudio",
    "playMissionPassedTune",
    "playObjectAnim",
    "playerEnteredBuildingsiteCrane",
    "playerEnteredDockCrane",
    "playerEnteredLasVegasCrane",
    "playerEnteredQuarryCrane",
    "playerLeftCrane",
    "playerMadeProgress",
    "playerTakeOffGoggles",
    "pointCameraAtCar",
    "pointCameraAtChar",
    "pointCameraAtPoint",
    "pointSearchlightAtChar",
    "pointSearchlightAtCoord",
    "pointSearchlightAtVehicle",
    "policeHeliChaseEntity",
    "popCarBoot",
    "popCarDoor",
    "popCarPanel",
    "preloadBeatTrack",
    "print",
    "printBig",
    "printBigQ",
    "printHelp",
    "printHelpConditional",
    "printHelpConditionalHid",
    "printHelpConditionalHidJoypad",
    "printHelpConditionalHidKeyboard",
    "printHelpConditionalTouch",
    "printHelpConditionalTouchAdapted",
    "printHelpConditionalTouchAnalog",
    "printHelpConditionalTouchClassic",
    "printHelpForever",
    "printHelpForeverConditional",
    "printHelpForeverConditionalHid",
    "printHelpForeverConditionalHidJoypad",
    "printHelpForeverConditionalHidKeyboard",
    "printHelpForeverConditionalTouch",
    "printHelpForeverConditionalTouchAdapted",
    "printHelpForeverConditionalTouchAnalog",
    "printHelpForeverConditionalTouchClassic",
    "printHelpForeverConditionalTouchDigital",
    "printHelpForeverConditionalTouchFlick",
    "printHelpForeverWithNumber",
    "printString",
    "printStringInStringNow",
    "printStringNow",
    "printStyledString",
    "printText",
    "printTextNow",
    "printWith2NumbersBig",
    "printWith2NumbersNow",
    "printWith3Numbers",
    "printWith4Numbers",
    "printWith4NumbersNow",
    "printWith6Numbers",
    "printWithNumber",
    "printWithNumberBig",
    "printWithNumberNow",
    "processLineOfSight",
    "raknetBitStreamDecodeString",
    "raknetBitStreamEncodeString",
    "raknetBitStreamGetDataPtr",
    "raknetBitStreamGetNumberOfBitsUsed",
    "raknetBitStreamGetNumberOfBytesUsed",
    "raknetBitStreamGetNumberOfUnreadBits",
    "raknetBitStreamGetReadOffset",
    "raknetBitStreamGetWriteOffset",
    "raknetBitStreamIgnoreBits",
    "raknetBitStreamReadBool",
    "raknetBitStreamReadBuffer",
    "raknetBitStreamReadFloat",
    "raknetBitStreamReadInt16",
    "raknetBitStreamReadInt32",
    "raknetBitStreamReadInt8",
    "raknetBitStreamReadString",
    "raknetBitStreamResetReadPointer",
    "raknetBitStreamResetWritePointer",
    "raknetBitStreamSetReadOffset",
    "raknetBitStreamSetWriteOffset",
    "raknetBitStreamWriteBitStream",
    "raknetBitStreamWriteBool",
    "raknetBitStreamWriteBuffer",
    "raknetBitStreamWriteFloat",
    "raknetBitStreamWriteInt16",
    "raknetBitStreamWriteInt32",
    "raknetBitStreamWriteInt8",
    "raknetBitStreamWriteString",
    "raknetDeleteBitStream",
    "raknetEmulPacketReceiveBitStream",
    "raknetEmulRpcReceiveBitStream",
    "raknetNewBitStream",
    "raknetResetBitStream",
    "raknetSendBitStream",
    "raknetSendBitStreamEx",
    "raknetSendRpc",
    "raknetSendRpcEx",
    "randomPassengerSay",
    "rawequal",
    "rawget",
    "rawset",
    "readKillFrenzyStatus",
    "readMemory",
    "registerAttractorScriptBrainForCodeUse",
    "registerBestPosition",
    "registerFastestTime",
    "registerFloatStat",
    "registerIntStat",
    "registerMissionGiven",
    "registerMissionPassed",
    "registerOddjobMissionPassed",
    "registerScriptBrainForCodeUse",
    "releaseAudioStream",
    "releaseEntityFromRopeForObject",
    "releaseEntityFromWinch",
    "releasePathNodes",
    "releaseTwoPlayerDistance",
    "releaseWeaponLock",
    "releaseWeather",
    "reloadScripts",
    "removeAllCharWeapons",
    "removeAllScriptFires",
    "removeAnimation",
    "removeBlip",
    "removeButtonFlag",
    "removeCarRecording",
    "removeCharElegantly",
    "removeCharFromCarMaintainPosition",
    "removeCharFromGroup",
    "removeDecisionMaker",
    "removeGroup",
    "removeIpl",
    "removeIplDiscreetly",
    "removeObjectElegantly",
    "removeOilPuddlesInArea",
    "removePickup",
    "removePriceModifier",
    "removeRcBuggy",
    "removeScriptFire",
    "removeSphere",
    "removeStreamedScript",
    "removeStuckCarCheck",
    "removeTextureDictionary",
    "removeUpsidedownCarCheck",
    "removeUser3dMarker",
    "removeVehicleMod",
    "removeWeaponFromChar",
    "removeWidgetFlag",
    "renderCreateFont",
    "renderDrawBox",
    "renderDrawBoxWithBorder",
    "renderDrawLine",
    "renderDrawPolygon",
    "renderDrawTexture",
    "renderFontDrawText",
    "renderGetFontDrawHeight",
    "renderGetFontDrawTextLength",
    "renderGetTextureSize",
    "renderLoadTextureFromFile",
    "renderLoadTextureFromFileInMemory",
    "renderReleaseFont",
    "renderReleaseTexture",
    "reportMissionAudioEventAtCar",
    "reportMissionAudioEventAtChar",
    "reportMissionAudioEventAtObject",
    "reportMissionAudioEventAtPosition",
    "representFloatAsInt",
    "representIntAsFloat",
    "requestAnimation",
    "requestCarRecording",
    "requestCollision",
    "requestIpl",
    "requestModel",
    "requestVehicleMod",
    "require",
    "resetNumOfModelsKilledByPlayer",
    "resetStuffUponResurrection",
    "resetVehicleCameraTweak",
    "resetVehicleHydraulics",
    "restoreCamera",
    "restoreCameraJumpcut",
    "restoreCarModState",
    "restoreClock",
    "restoreClothesState",
    "rotateObject",
    "sampAddChatMessage",
    "sampCreate3dText",
    "sampCreate3dTextEx",
    "sampDestroy3dText",
    "sampGet3dTextInfoById",
    "sampGetCarHandleBySampVehicleId",
    "sampGetCharHandleBySampPlayerId",
    "sampGetCurrentDialogId",
    "sampGetCurrentDialogType",
    "sampGetCurrentServerAddress",
    "sampGetCurrentServerName",
    "sampGetDialogCaption",
    "sampGetDialogText",
    "sampGetMaxPlayerId",
    "sampGetObjectHandleBySampId",
    "sampGetObjectSampIdByHandle",
    "sampGetPlayerAnimationId",
    "sampGetPlayerArmor",
    "sampGetPlayerColor",
    "sampGetPlayerCount",
    "sampGetPlayerHealth",
    "sampGetPlayerIdByCharHandle",
    "sampGetPlayerNickname",
    "sampGetPlayerPing",
    "sampGetPlayerScore",
    "sampGetPlayerSpecialAction",
    "sampGetVehicleIdByCarHandle",
    "sampHasDialogRespond",
    "sampIs3dTextDefined",
    "sampIsChatCommandDefined",
    "sampIsDialogActive",
    "sampIsDialogClientside",
    "sampIsLocalPlayerSpawned",
    "sampIsPlayerConnected",
    "sampIsPlayerNpc",
    "sampIsPlayerPaused",
    "sampProcessChatInput",
    "sampRegisterChatCommand",
    "sampRequestClass",
    "sampSendAimData",
    "sampSendBulletData",
    "sampSendChat",
    "sampSendClickPlayer",
    "sampSendClickTextdraw",
    "sampSendDamageVehicle",
    "sampSendDeathByPlayer",
    "sampSendDialogResponse",
    "sampSendEditAttachedObject",
    "sampSendEditObject",
    "sampSendEnterVehicle",
    "sampSendExitVehicle",
    "sampSendGiveDamage",
    "sampSendIncarData",
    "sampSendInteriorChange",
    "sampSendMenuQuit",
    "sampSendMenuSelectRow",
    "sampSendOnfootData",
    "sampSendPassengerData",
    "sampSendPickedUpPickup",
    "sampSendRconCommand",
    "sampSendRequestSpawn",
    "sampSendScmEvent",
    "sampSendSpawn",
    "sampSendSpectatorData",
    "sampSendTakeDamage",
    "sampSendTrailerData",
    "sampSendUnoccupiedData",
    "sampSendVehicleDestroyed",
    "sampSet3dTextString",
    "sampSetClientCommandDescription",
    "sampSetDialogClientside",
    "sampSetSpecialAction",
    "sampShowDialog",
    "sampSpawnPlayer",
    "sampStorePlayerAimData",
    "sampStorePlayerIncarData",
    "sampStorePlayerOnfootData",
    "sampStorePlayerPassengerData",
    "sampStorePlayerTrailerData",
    "sampUnregisterChatCommand",
    "script_author",
    "script_authors",
    "script_dependencies",
    "script_description",
    "script_moonloader",
    "script_name",
    "script_properties",
    "script_url",
    "script_version",
    "script_version_number",
    "select",
    "selectWeaponsForVehicle",
    "setActiveMenuItem",
    "setActiveMenuItemCarMods",
    "setAircraftCarrierSamSite",
    "setAllCarsCanBeDamaged",
    "setAllTaxisHaveNitro",
    "setAlwaysDraw3dMarkers",
    "setAnimGroupForChar",
    "setArea51SamSite",
    "setAreaName",
    "setAudioStreamLooped",
    "setAudioStreamState",
    "setAudioStreamVolume",
    "setBlipAlwaysDisplayOnZoomedRadar",
    "setBlipAsFriendly",
    "setBlipEntryExit",
    "setBoatCruiseSpeed",
    "setCameraBehindPlayer",
    "setCameraInFrontOfChar",
    "setCameraInFrontOfPlayer",
    "setCameraPositionUnfixed",
    "setCameraZoom",
    "setCanBurstCarTires",
    "setCanResprayCar",
    "setCarAlwaysCreateSkids",
    "setCarAsMissionCar",
    "setCarAvoidLevelTransitions",
    "setCarCanBeDamaged",
    "setCarCanBeVisiblyDamaged",
    "setCarCanGoAgainstTraffic",
    "setCarCollision",
    "setCarCoordinates",
    "setCarCoordinatesNoOffset",
    "setCarCruiseSpeed",
    "setCarDensityMultiplier",
    "setCarDrivingStyle",
    "setCarEngineBroken",
    "setCarEngineOn",
    "setCarEscortCarFront",
    "setCarEscortCarLeft",
    "setCarEscortCarRear",
    "setCarEscortCarRight",
    "setCarFollowCar",
    "setCarForwardSpeed",
    "setCarHeading",
    "setCarHealth",
    "setCarHeavy",
    "setCarHydraulics",
    "setCarLightsOn",
    "setCarMission",
    "setCarModelComponents",
    "setCarOnlyDamagedByPlayer",
    "setCarProofs",
    "setCarRandomRouteSeed",
    "setCarRoll",
    "setCarRotationVelocity",
    "setCarStatus",
    "setCarStayInFastLane",
    "setCarStayInSlowLane",
    "setCarStraightLineDistance",
    "setCarStrong",
    "setCarTempAction",
    "setCarTraction",
    "setCarVisible",
    "setCarWatertight",
    "setCharAccuracy",
    "setCharAllowedToDuck",
    "setCharAmmo",
    "setCharAnimCurrentTime",
    "setCharAnimPlayingFlag",
    "setCharAnimSpeed",
    "setCharBleeding",
    "setCharBulletproofVest",
    "setCharCanBeKnockedOffBike",
    "setCharCanBeShotInVehicle",
    "setCharCantBeDraggedOut",
    "setCharCollision",
    "setCharCoordinates",
    "setCharCoordinatesDontWarpGang",
    "setCharCoordinatesDontWarpGangNoOffset",
    "setCharCoordinatesNoOffset",
    "setCharDecisionMaker",
    "setCharDropsWeaponsWhenDead",
    "setCharDrownsInWater",
    "setCharDruggedUp",
    "setCharForceDieInCar",
    "setCharGetOutUpsideDownCar",
    "setCharHasUsedEntryExit",
    "setCharHeading",
    "setCharHealth",
    "setCharInterior",
    "setCharIsChrisCriminal",
    "setCharIsTargetPriority",
    "setCharKeepTask",
    "setCharKindaStayInSamePlace",
    "setCharMaxHealth",
    "setCharMoney",
    "setCharNeverLeavesGroup",
    "setCharNeverTargetted",
    "setCharOnlyDamagedByPlayer",
    "setCharProofs",
    "setCharQuaternion",
    "setCharRelationship",
    "setCharRotation",
    "setCharSayContext",
    "setCharSayContextImportant",
    "setCharSayScript",
    "setCharShootRate",
    "setCharSignalAfterKill",
    "setCharStayInCarWhenJacked",
    "setCharStayInSamePlace",
    "setCharSuffersCriticalHits",
    "setCharSwimSpeed",
    "setCharUsesCollisionClosestObjectOfType",
    "setCharUsesUpperbodyDamageAnimsOnly",
    "setCharVelocity",
    "setCharVisible",
    "setCharWantedByPolice",
    "setCharWeaponSkill",
    "setCheckpointCoords",
    "setCheckpointHeading",
    "setCinemaCamera",
    "setClipboardText",
    "setClosestEntryExitFlag",
    "setCollectable1Total",
    "setCoordBlipAppearance",
    "setCreateRandomCops",
    "setCreateRandomGangMembers",
    "setCurrentCharWeapon",
    "setCutsceneModelTexture",
    "setCutsceneOffset",
    "setDarknessEffect",
    "setDeathWeaponsPersist",
    "setDeatharrestState",
    "setDisableMilitaryZones",
    "setDrunkInputDelay",
    "setEnableRcDetonate",
    "setEnableRcDetonateOnContact",
    "setEquippedItem",
    "setEveryoneIgnorePlayer",
    "setExtraCarColours",
    "setExtraColours",
    "setExtraHospitalRestartPoint",
    "setExtraPoliceStationRestartPoint",
    "setFadingColour",
    "setFirstPersonInCarCameraMode",
    "setFixedCameraPosition",
    "setFloatStat",
    "setFollowNodeThresholdDistance",
    "setForceRandomCarModel",
    "setFreeGxtEntry",
    "setFreeHealthCare",
    "setFreeResprays",
    "setFreebiesInVehicle",
    "setGameKeyState",
    "setGangWarsActive",
    "setGangWarsTrainingMission",
    "setGangWeapons",
    "setGarageResprayFree",
    "setGroupDecisionMaker",
    "setGroupDefaultTaskAllocator",
    "setGroupFollowStatus",
    "setGroupLeader",
    "setGroupMember",
    "setGroupSeparationRange",
    "setGroupSequence",
    "setGunshotSenseRangeForRiot2",
    "setGxtEntry",
    "setHasBeenOwnedForCarGenerator",
    "setHeadingForAttachedPlayer",
    "setHeadingLimitForAttachedChar",
    "setHeathazeEffect",
    "setHeliBladesFullSpeed",
    "setHeliOrientation",
    "setHeliReachedTargetDistance",
    "setHeliStabiliser",
    "setHelpMessageBoxSize",
    "setInformRespectedFriends",
    "setInfraredVision",
    "setIntStat",
    "setInteriorVisible",
    "setInterpolationParameters",
    "setLaRiots",
    "setLoadCollisionForCarFlag",
    "setLoadCollisionForCharFlag",
    "setMaxFireGenerations",
    "setMaxWantedLevel",
    "setMenuColumn",
    "setMenuColumnOrientation",
    "setMenuColumnWidth",
    "setMenuItemWith2Numbers",
    "setMenuItemWithNumber",
    "setMessageFormatting",
    "setMinigameInProgress",
    "setMissionAudioPosition",
    "setMissionRespectTotal",
    "setMissionTrainCoordinates",
    "setMusicDoesFade",
    "setNamedEntryExitFlag",
    "setNearClip",
    "setNextDesiredMoveState",
    "setNightVision",
    "setNoResprays",
    "setObjectAnimCurrentTime",
    "setObjectAnimSpeed",
    "setObjectAsStealable",
    "setObjectCollision",
    "setObjectCollisionDamageEffect",
    "setObjectCoordinates",
    "setObjectCoordinatesAndVelocity",
    "setObjectDrawLast",
    "setObjectDynamic",
    "setObjectHeading",
    "setObjectHealth",
    "setObjectMass",
    "setObjectOnlyDamagedByPlayer",
    "setObjectProofs",
    "setObjectQuaternion",
    "setObjectRecordsCollisions",
    "setObjectRenderScorched",
    "setObjectRotation",
    "setObjectRotationVelocity",
    "setObjectScale",
    "setObjectTurnMass",
    "setObjectVelocity",
    "setObjectVisible",
    "setOnlyCreateGangMembers",
    "setOnscreenCounterFlashWhenFirstDisplayed",
    "setPedDensityMultiplier",
    "setPetrolTankWeakpoint",
    "setPhotoCameraEffect",
    "setPlaneThrottle",
    "setPlaneUndercarriageUp",
    "setPlay3dAudioStreamAtCar",
    "setPlay3dAudioStreamAtChar",
    "setPlay3dAudioStreamAtCoordinates",
    "setPlay3dAudioStreamAtObject",
    "setPlaybackSpeed",
    "setPlayerCanDoDriveBy",
    "setPlayerControl",
    "setPlayerDisplayVitalStatsButton",
    "setPlayerDrunkenness",
    "setPlayerDuckButton",
    "setPlayerEnterCarButton",
    "setPlayerFastReload",
    "setPlayerFireButton",
    "setPlayerGroupRecruitment",
    "setPlayerGroupToFollowAlways",
    "setPlayerGroupToFollowNever",
    "setPlayerInCarCameraMode",
    "setPlayerIsInStadium",
    "setPlayerJumpButton",
    "setPlayerModel",
    "setPlayerMood",
    "setPlayerNeverGetsTired",
    "setPlayerPlayerTargetting",
    "setPlayerWeaponsScrollable",
    "setPlayersCanBeInSeparateCars",
    "setPoliceIgnorePlayer",
    "setPoolTableCoords",
    "setProgressTotal",
    "setRadarZoom",
    "setRadioChannel",
    "setRadioToPlayersFavouriteStation",
    "setRailtrackResistanceMult",
    "setRelationship",
    "setRespawnPointForDurationOfMission",
    "setRopeHeightForObject",
    "setScriptCoopGame",
    "setScriptLimitToGangSize",
    "setSearchlightClipIfColliding",
    "setSenseRange",
    "setSequenceToRepeat",
    "setSliderRange",
    "setSpecificZoneToTriggerGangWar",
    "setSpritesDrawBeforeFade",
    "setStructElement",
    "setStructFloatElement",
    "setTagStatusInArea",
    "setTargetCarForMissionGarage",
    "setTaxiLights",
    "setTextBackground",
    "setTextCentre",
    "setTextCentreSize",
    "setTextColour",
    "setTextDrawBeforeFade",
    "setTextDropshadow",
    "setTextEdge",
    "setTextFont",
    "setTextJustify",
    "setTextProportional",
    "setTextRightJustify",
    "setTextScale",
    "setTextWrapx",
    "setTimeOfDay",
    "setTimeOneDayForward",
    "setTimeScale",
    "setTimerBeepCountdownTime",
    "setTotalNumberOfMissions",
    "setTrainCruiseSpeed",
    "setTrainForcedToSlowDown",
    "setTrainSpeed",
    "setTwoPlayerCameraMode",
    "setUpConversationEndNodeWithScriptedSpeech",
    "setUpConversationEndNodeWithSpeech",
    "setUpConversationNodeWithScriptedSpeech",
    "setUpConversationNodeWithSpeech",
    "setUpSkip",
    "setUpSkipAfterMission",
    "setUpSkipForSpecificVehicle",
    "setUpSkipForVehicleFinishedByScript",
    "setUpsidedownCarNotDamaged",
    "setUsesCollisionOfClosestObjectOfType",
    "setVehicleAirResistanceMultiplier",
    "setVehicleCameraTweak",
    "setVehicleCanBeTargetted",
    "setVehicleDirtLevel",
    "setVehicleInterior",
    "setVehicleIsConsideredByPlayer",
    "setVehicleQuaternion",
    "setVehicleToFadeIn",
    "setVisibilityOfClosestObjectOfType",
    "setWantedMultiplier",
    "setWeatherToAppropriateTypeNow",
    "setWidgetInfo",
    "setWidgetInfo2",
    "setWidgetSliderRange",
    "setWidgetTexture",
    "setWidgetValue",
    "setWidgetValue2",
    "setWidgetValue3",
    "setZoneDealerStrength",
    "setZoneForGangWarsTraining",
    "setZoneGangStrength",
    "setZoneNoCops",
    "setZonePopulationRace",
    "setZonePopulationType",
    "setfenv",
    "setmetatable",
    "shakeCam",
    "shakePad",
    "showBlipsOnAllLevels",
    "showUpdateStats",
    "shuffleCardDecks",
    "shutAllCharsUp",
    "shutCharUp",
    "shutCharUpForScriptedSpeech",
    "skipCutsceneEnd",
    "skipInPlaybackRecordedCar",
    "skipToEndAndStopPlaybackRecordedCar",
    "skipToNextAllowedStation",
    "slideObject",
    "sortOutObjectCollisionWithCar",
    "startCarFire",
    "startCharFacialTalk",
    "startCharFire",
    "startCredits",
    "startCutscene",
    "startKillFrenzy",
    "startNewStreamedScript",
    "startPlaybackRecordedCar",
    "startPlaybackRecordedCarLooped",
    "startPlaybackRecordedCarUsingAi",
    "startScriptFire",
    "startSettingUpConversation",
    "stopBeatTrack",
    "stopCharFacialTalk",
    "stopCredits",
    "stopFxSystem",
    "stopPlaybackRecordedCar",
    "storeCarCharIsAttachedToNoSave",
    "storeCarCharIsIn",
    "storeCarCharIsInNoSave",
    "storeCarModState",
    "storeClock",
    "storeClosestEntities",
    "storeClothesState",
    "storeWantedLevel",
    "streamScript",
    "suppressCarModel",
    "swapNearestBuildingModel",
    "switchAmbientPlanes",
    "switchArrestPenalties",
    "switchAudioZone",
    "switchCarEngine",
    "switchCarGenerator",
    "switchCarSiren",
    "switchCopsOnBikes",
    "switchDeathPenalties",
    "switchEmergencyServices",
    "switchEntryExit",
    "switchObjectBrains",
    "switchOnGroundSearchlight",
    "switchPedRoadsBackToOriginal",
    "switchPedRoadsOff",
    "switchPedRoadsOn",
    "switchPoliceHelis",
    "switchRandomTrains",
    "switchRoadsBackToOriginal",
    "switchRoadsOff",
    "switchRoadsOn",
    "switchStreaming",
    "switchWidescreen",
    "switchWorldProcessing",
    "syncWater",
    "takePhoto",
    "takeRemoteControlOfCar",
    "taskAchieveHeading",
    "taskAimGunAtChar",
    "taskAimGunAtCoord",
    "taskCarDriveToCoord",
    "taskCarDriveWander",
    "taskCarMission",
    "taskCarTempAction",
    "taskCharArrestChar",
    "taskCharSlideToCoord",
    "taskCharSlideToCoordAndPlayAnim",
    "taskChatWithChar",
    "taskClimb",
    "taskComplexPickupObject",
    "taskCower",
    "taskDead",
    "taskDestroyCar",
    "taskDie",
    "taskDieNamedAnim",
    "taskDiveAndGetUp",
    "taskDiveFromAttachmentAndGetUp",
    "taskDriveBy",
    "taskDrivePointRoute",
    "taskDrivePointRouteAdvanced",
    "taskDuck",
    "taskEnterCarAsDriver",
    "taskEnterCarAsPassenger",
    "taskEveryoneLeaveCar",
    "taskFallAndGetUp",
    "taskFleeChar",
    "taskFleeCharAnyMeans",
    "taskFleePoint",
    "taskFollowFootsteps",
    "taskFollowPathNodesToCoord",
    "taskFollowPathNodesToCoordWithRadius",
    "taskFollowPatrolRoute",
    "taskFollowPointRoute",
    "taskGoStraightToCoord",
    "taskGoToCoordAnyMeans",
    "taskGoToCoordWhileAiming",
    "taskGoToCoordWhileShooting",
    "taskGoToObject",
    "taskGotoCar",
    "taskGotoChar",
    "taskGotoCharAiming",
    "taskGotoCharOffset",
    "taskGreetPartner",
    "taskHandGesture",
    "taskHandsUp",
    "taskJetpack",
    "taskJump",
    "taskKillCharOnFoot",
    "taskKillCharOnFootTimed",
    "taskKillCharOnFootWhileDucking",
    "taskKindaStayInSamePlace",
    "taskLeaveAnyCar",
    "taskLeaveCar",
    "taskLeaveCarAndFlee",
    "taskLeaveCarImmediately",
    "taskLookAbout",
    "taskLookAtChar",
    "taskLookAtCoord",
    "taskLookAtObject",
    "taskLookAtVehicle",
    "taskPause",
    "taskPickUpObject",
    "taskPickUpSecondObject",
    "taskPlayAnim",
    "taskPlayAnimNonInterruptable",
    "taskPlayAnimSecondary",
    "taskPlayAnimWithFlags",
    "taskSay",
    "taskScratchHead",
    "taskSetCharDecisionMaker",
    "taskSetIgnoreWeaponRangeFlag",
    "taskShakeFist",
    "taskShootAtChar",
    "taskShootAtCoord",
    "taskShuffleToNextCarSeat",
    "taskSitDown",
    "taskSmartFleeChar",
    "taskSmartFleePoint",
    "taskStandStill",
    "taskStayInSamePlace",
    "taskSwimToCoord",
    "taskTired",
    "taskToggleDuck",
    "taskTogglePedThreatScanner",
    "taskTurnCharToFaceChar",
    "taskTurnCharToFaceCoord",
    "taskUseAtm",
    "taskUseAttractor",
    "taskUseClosestMapAttractor",
    "taskUseMobilePhone",
    "taskWalkAlongsideChar",
    "taskWanderStandard",
    "taskWarpCharIntoCarAsDriver",
    "taskWarpCharIntoCarAsPassenger",
    "taskWeaponRoll",
    "thisScript",
    "tonumber",
    "tostring",
    "turnCarToFaceCoord",
    "type",
    "unloadSpecialCharacter",
    "unlockAchievement",
    "unmarkAllRoadNodesAsDontWander",
    "unpack",
    "unpausePlaybackRecordedCar",
    "updatePickupMoneyPerDay",
    "useDetonator",
    "useRenderCommands",
    "vehicleCanBeTargettedByHsMissile",
    "vehicleDoesProvideCover",
    "wait",
    "warpCharFromCarToCoord",
    "warpCharIntoCar",
    "warpCharIntoCarAsPassenger",
    "wasCutsceneSkipped",
    "winchCanPickObjectUp",
    "winchCanPickVehicleUp",
    "writeLog",
    "writeLogFloat",
    "writeLogInt",
    "writeMemory",
    "xpcall",
    NULL
};

// Binary search helper (array sudah sorted)
static bool isGlobalAPI(const char* name) {
    if (!name) return false;
    int lo = 0, hi = 1753;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = strcmp(GLOBAL_API[mid], name);
        if (cmp == 0) return true;
        if (cmp < 0)  lo = mid + 1;
        else          hi = mid - 1;
    }
    return false;
}

// ── Buffer deduplicated ───────────────────────────────────────
#define MAX_FUNCS 512
#define FUNC_LEN  64

static char   g_funcs[MAX_FUNCS][FUNC_LEN];
static int    g_func_count = 0;
static bool   g_dirty      = false;
static pthread_mutex_t g_mutex = PTHREAD_MUTEX_INITIALIZER;

static void writeLog(const char* msg) {
    FILE* f = fopen("/sdcard/luadbg.log", "a");
    if (f) { fprintf(f, "%s\n", msg); fclose(f); }
}

static void addFunc(const char* name) {
    for (int i = 0; i < g_func_count; i++)
        if (strcmp(g_funcs[i], name) == 0) return;
    if (g_func_count >= MAX_FUNCS) return;
    strncpy(g_funcs[g_func_count++], name, FUNC_LEN-1);
    g_dirty = true;
}

static void flush() {
    if (!g_dirty) return;
    FILE* f = fopen("/sdcard/luadbg_funcs.txt", "w");
    if (!f) return;
    fprintf(f, "=== API global yang dipanggil oleh: %s ===\n", g_target);
    fprintf(f, "Total: %d fungsi\n\n", g_func_count);
    for (int i = 0; i < g_func_count; i++)
        fprintf(f, "%s\n", g_funcs[i]);
    fclose(f);
    g_dirty = false;
}

// ── Cek apakah source adalah target script ───────────────────
static bool sourceIsTarget(const char* source) {
    if (!source) return false;
    const char* s = (source[0] == '@') ? source+1 : source;
    const char* base = strrchr(s, '/');
    base = base ? base+1 : s;
    return strstr(base, g_target) != NULL;
}

// ── Hook ──────────────────────────────────────────────────────
extern "C" __attribute__((visibility("default")))
void LuaDebugger_hook(lua_State* L, lua_Debug* ar) {
    if (!g_getinfo || !g_target[0]) return;
    g_getinfo(L, "nS", ar);

    if (!ar->name) return;
    if (!isGlobalAPI(ar->name)) return;

    // Untuk C function (=[C]), source-nya bukan script — cek caller
    bool fromTarget = false;
    if (ar->source && ar->source[0] != '=') {
        // Lua function — cek source langsung
        fromTarget = sourceIsTarget(ar->source);
    } else if (g_getstack) {
        // C function — cek siapa yang memanggil
        lua_Debug caller;
        memset(&caller, 0, sizeof(caller));
        if (g_getstack(L, 1, &caller) && g_getinfo(L, "S", &caller)) {
            fromTarget = sourceIsTarget(caller.source);
        }
    }

    if (!fromTarget) return;

    pthread_mutex_lock(&g_mutex);
    addFunc(ar->name);
    pthread_mutex_unlock(&g_mutex);
}

extern "C" __attribute__((visibility("default")))
lua_State* LuaDebugger_newstate_hook(void) {
    lua_State* L = g_orig_newstate();
    if (L && g_sethook) {
        void* fn = dlsym(RTLD_DEFAULT, "LuaDebugger_hook");
        if (fn) g_sethook(L, (lua_Hook)fn, LUA_MASKCALL, 0);
    }
    return L;
}

static void* flushThread(void*) {
    while (true) {
        sleep(3);
        pthread_mutex_lock(&g_mutex);
        flush();
        pthread_mutex_unlock(&g_mutex);
    }
    return NULL;
}

// ── Helpers ──────────────────────────────────────────────────
static uintptr_t getLibBase(const char* name) {
    FILE* f = fopen("/proc/self/maps", "r");
    if (!f) return 0;
    char line[512]; uintptr_t base = (uintptr_t)-1;
    while (fgets(line, sizeof(line), f)) {
        if (!strstr(line, name)) continue;
        uintptr_t s = (uintptr_t)strtoul(line, NULL, 16);
        if (s < base) base = s;
    }
    fclose(f);
    return (base == (uintptr_t)-1) ? 0 : base;
}

static bool getSelfPath(char* out, size_t sz) {
    FILE* f = fopen("/proc/self/maps", "r");
    if (!f) return false;
    char line[512];
    while (fgets(line, sizeof(line), f)) {
        if (!strstr(line, "libLuaDebugger.so")) continue;
        char* path = strstr(line, "/data");
        if (!path) continue;
        size_t len = strlen(path);
        if (path[len-1] == '\n') path[len-1] = '\0';
        strncpy(out, path, sz-1);
        fclose(f); return true;
    }
    fclose(f); return false;
}

static bool patchGOT(uintptr_t base, const char* sym, void* fn) {
    Elf32_Ehdr* ehdr = (Elf32_Ehdr*)base;
    if (ehdr->e_ident[0] != 0x7f) return false;
    Elf32_Phdr* phdr = (Elf32_Phdr*)(base + ehdr->e_phoff);
    Elf32_Dyn* dyn = NULL;
    for (int i = 0; i < ehdr->e_phnum; i++)
        if (phdr[i].p_type == PT_DYNAMIC) { dyn = (Elf32_Dyn*)(base + phdr[i].p_vaddr); break; }
    if (!dyn) return false;
    Elf32_Sym* symtab = NULL; const char* strtab = NULL;
    Elf32_Rel* jmprel = NULL; size_t jmprel_sz = 0;
    for (Elf32_Dyn* d = dyn; d->d_tag != DT_NULL; d++) {
        if (d->d_tag == DT_SYMTAB)   symtab    = (Elf32_Sym*)(base + d->d_un.d_ptr);
        if (d->d_tag == DT_STRTAB)   strtab    = (const char*)(base + d->d_un.d_ptr);
        if (d->d_tag == DT_JMPREL)   jmprel    = (Elf32_Rel*)(base + d->d_un.d_ptr);
        if (d->d_tag == DT_PLTRELSZ) jmprel_sz = d->d_un.d_val;
    }
    if (!symtab || !strtab || !jmprel) return false;
    for (size_t i = 0; i < jmprel_sz / sizeof(Elf32_Rel); i++) {
        uint32_t idx = ELF32_R_SYM(jmprel[i].r_info);
        if (strcmp(strtab + symtab[idx].st_name, sym) != 0) continue;
        uint32_t* got = (uint32_t*)(base + jmprel[i].r_offset);
        uintptr_t page = (uintptr_t)got & ~((uintptr_t)(getpagesize()-1));
        mprotect((void*)page, getpagesize(), PROT_READ | PROT_WRITE);
        *got = (uint32_t)(uintptr_t)fn;
        mprotect((void*)page, getpagesize(), PROT_READ);
        return true;
    }
    return false;
}

__attribute__((constructor))
static void onLoad() {
    writeLog("=== LuaDebugger START ===");
    static int initialized = 0;
    if (initialized) return;
    initialized = 1;

    FILE* cfg = fopen("/sdcard/luadbg_config.txt", "r");
    if (cfg) {
        char line[256];
        while (fgets(line, sizeof(line), cfg)) {
            line[strcspn(line, "\r\n")] = 0;
            if (strncmp(line, "target=", 7) == 0)
                strncpy(g_target, line+7, sizeof(g_target)-1);
        }
        fclose(cfg);
    }

    if (!g_target[0]) {
        writeLog("[CONFIG] Buat /sdcard/luadbg_config.txt, isi: target=namaScript.lua");
        return;
    }
    char buf[128];
    snprintf(buf, sizeof(buf), "[CONFIG] target=%s", g_target);
    writeLog(buf);

    void* luajit = dlopen("libluajit-5.1.so", RTLD_NOW | RTLD_GLOBAL);
    if (!luajit) { writeLog("[LuaJIT] FAILED"); return; }

    g_orig_newstate = (luaL_newstate_t)dlsym(luajit, "luaL_newstate");
    g_sethook       = (lua_sethook_t)  dlsym(luajit, "lua_sethook");
    g_getinfo       = (lua_getinfo_t)  dlsym(luajit, "lua_getinfo");
    g_getstack      = (lua_getstack_t) dlsym(luajit, "lua_getstack");
    if (!g_orig_newstate || !g_sethook || !g_getinfo) {
        writeLog("[LuaJIT] symbol FAILED"); return;
    }

    dlopen("libmonetloader.so", RTLD_NOW | RTLD_GLOBAL);

    char selfPath[512] = {0};
    getSelfPath(selfPath, sizeof(selfPath));
    if (!selfPath[0]) strcpy(selfPath, "libLuaDebugger.so");

    void* self = dlopen(selfPath, RTLD_NOW | RTLD_GLOBAL);
    if (!self) { writeLog("[Self] FAILED"); return; }

    void* hookFn = dlsym(self, "LuaDebugger_newstate_hook");
    if (!hookFn) hookFn = dlsym(RTLD_DEFAULT, "LuaDebugger_newstate_hook");
    if (!hookFn) { writeLog("[Self] hook FAILED"); return; }

    uintptr_t thumb = ((uintptr_t)hookFn & ~1u) | 1u;
    uintptr_t base  = getLibBase("libmonetloader.so");
    if (!base) { writeLog("[GOT] base FAILED"); return; }

    if (patchGOT(base, "luaL_newstate", (void*)thumb)) {
        writeLog("[GOT] Patch SUCCESS");
        snprintf(buf, sizeof(buf), "[INFO] Tracking %d global API functions", 1754);
        writeLog(buf);
        writeLog("[INFO] Output: /sdcard/luadbg_funcs.txt");

        pthread_t tid;
        pthread_create(&tid, NULL, flushThread, NULL);
        pthread_detach(tid);
    }
}
